### ISSUE TITLE
dataset in paper

### ISSUE THREAD

**Issue by HaoranDeng** [Josiah96Zhang/Lemane#2]
Hello, we found that most of the data under the data folder is empty, is it possible that we can get the data in the paper?
We would like to get WikiVte and Slashdot datasets, thanks a lot!

**Comment by Josiah96Zhang** [comment]
Hi Haoran, 
You can get these two datasets from https://github.com/yinyuan1227/STRAP-git.

**Comment by HaoranDeng** [comment]
Thank you very much for your reply, I found these datasets from the link you provided.
